name: Pre-Production Performance Testing

on:
  push:
    branches:
      - main  # Runs after PR is merged into main

jobs:
  preprod-perf-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java (required by JMeter)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install JMeter
        run: |
          sudo apt update
          sudo apt install -y jmeter
          jmeter --version

      - name: Run JMeter Test
        run: |
          mkdir -p reports/jmeter
          jmeter -n -t tests/perf_test.jmx -l reports/jmeter/results.jtl -e -o reports/jmeter/report

      - name: Upload JMeter HTML Report
        uses: actions/upload-artifact@bcb6a651d2b8c4fdb17bcf0d2581a3ad16f58aa9  # Pin to known good SHA
        with:
          name: jmeter-report
          path: reports/jmeter/report
