name: Gitea Preproduction Performance Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprod-performance-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        options: --health-cmd="pg_isready -U gitea_user" --health-timeout=30s --health-retries=3
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: gitea
          POSTGRES_USER: gitea_user
          POSTGRES_PASSWORD: gitea_pass

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for preprod
        run: |
          docker build -t maias816/myapp:preprod .

      - name: Push Docker image to Docker Hub
        run: |
          docker push maias816/myapp:preprod

      - name: Run preproduction tests
        run: |
          docker run --rm maias816/myapp:preprod ./run_preprod_tests.sh

      - name: Install k6 performance testing tool
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg2 software-properties-common
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run k6 performance test
        run: |
          k6 run tests/performance_test.js
